export enum zIndexEnum {
  COOKIE_POLICY_BANNER = 1020,
  MAIN_OVERLAY = 1010,
  BREADCRUMB = 1000,
  HOME_BUTTON = 100,
  HEADER_PAGE = 10,
  OVERLAY_MOBILE_TOOLTIP = 8,
  ECHART_TOOL_TIP = 6,
  SMALL_ICON_AVATAR_WITH_ICON_COMPONENT = 4,
  CORE_UNIT_SUMMARY = 3,
  DELEGATE_SUMMARY = 3,
  NAVIGATION_CARDS = 2,
}
