name: Staging deployment

on:
  push:
    branches: [ sky-staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      matrix:
        node-version: [v20.9.0]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Configure environment variables
        run: |
          echo -e "NEXT_PUBLIC_GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_API_URL }}\nNEXT_PUBLIC_ENVIRONMENT=staging\nENABLE_SITEMAP=true\nNEXT_PUBLIC_BASE_URL=https://staging.fusion.phd\nNEXT_PUBLIC_CONNECT=${{ secrets.NEXT_PUBLIC_CONNECT }}\n" >> .env
      - name: Install project
        run: |
          npm install -g yarn
          yarn
          yarn build
      - name: Copy file via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASS }}
          source: "./"
          target: "/var/www/next/app-staging-tmp"
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS }}
          script: |
            pm2 stop next-js-staging
            mv /var/www/next/app-staging /var/www/next/app-staging-del
            mv /var/www/next/app-staging-tmp /var/www/next/app-staging
            pm2 start next-js-staging
            rm -rf /var/www/next/app-staging-del
